# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Outdated Dependencies

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Outdated_Dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Install PHP
        uses: shivammathur/setup-php@2.3.0
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Validate Composer
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --no-suggest

      - name: Check Outdated Dependencies
        run: composer outdated --direct
